name: Notification Discord

on:
  push:
    branches:
      - main  

jobs:
  discord-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: Ilshidur/action-discord@0.3.2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: | 
            nouveau commit sur la branche **main** sur le repo `${{ github.repository }}`
            url: https://faydonk.dev
          
